В данной программе есть ветвление if - else, а значит есть два пути выполнения программы без вызова исключений. (2)
Теперь рассмотрим в каких местах возможны исключения.
Исключение может вызвать аргумент нашей функции.(3)
Обращение к функциям-членам e.title() и e.salary() может спровоцировать исключение. (5)
Операции сравнения возвращаемых этими функциями-членами объектов могут вызвать исключение. (7)
Далее рассмотрим ветку if(true):
Равно как обращение к функциям-членам e.name(), e.surname(), так и применение к ним операторов вывода может вызвать исключение. (11)
Далее обращуние к e.name() и e.surname() уже не вызовет исключения, так как они сработали бы раньше, но из может вызвать оператор суммирования для каждого из них. (13)
Финальным для данной ветки местом, где может быть вызвано исключение будет являться return полученного суммированием значения. (14) 
Рассмотрим ветку if(false):
Здесь функция-член e.name() и оператор ее вывода могут вызвать по исключению. (16)
Обращение к e.surname() может вызвать исключение. (17)
Аналогично финалу предыдущей ветки, получим еще 3 места для иключения: два от суммы и один от финального return. (20)
Таким образом, получилось всего 20 возможных вариантов выполнения программы.
